// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sseujjilqpbklnlepqxq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzZXVqamlscXBia2xubGVwcXhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyOTI3MTUsImV4cCI6MjA1ODg2ODcxNX0.-1bA1QxJItXlp8K86xOCtUO-2JJ97VNZlrvVoz7Wqjs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);